// Code generated by cmd/codegen from https://github.com/AllenDang/cimgui-go.
// DO NOT EDIT.

#include "cimguizmo_wrapper.h"
#include "cimgui/cimguizmo.h"

bool wrap_Manipulate(const float* view,const float* projection,OPERATION operation,MODE mode,float* matrix) { return Manipulate(view,projection,operation,mode,matrix,0,0,0,0); }
void wrap_SetDrawlist() { SetDrawlist(0); }
