// Code generated by cmd/codegen from https://github.com/AllenDang/cimgui-go.
// DO NOT EDIT.

package imgui

// #include <stdlib.h>
// #include <memory.h>
// #include "extra_types.h"
// #include "cimguizmo_wrapper.h"
// #include "cimguizmo_typedefs.h"
import "C"

type Style struct {
	CData *C.Style
}

func (self *Style) handle() (result *C.Style, fin func()) {
	return self.CData, func() {}
}

func (self Style) c() (C.Style, func()) {
	result, fn := self.handle()
	return *result, fn
}

func newStyleFromC(cvalue *C.Style) *Style {
	return &Style{CData: cvalue}
}
