// Code generated by cmd/codegen from https://github.com/AllenDang/cimgui-go.
// DO NOT EDIT.


#pragma once

#include "cimgui/cimgui.h"

#ifdef __cplusplus
extern "C" {
#endif

extern void callbackDrawCallback(ImDrawList* parent_list, ImDrawCmd* cmd);

extern void callbackContextHookCallback(ImGuiContext* ctx, ImGuiContextHook* hook);

extern int callbackInputTextCallback(ImGuiInputTextCallbackData* data);

extern void callbackSizeCallback(ImGuiSizeCallbackData* data);

#ifdef __cplusplus
}
#endif