// Code generated by cmd/codegen from https://github.com/AllenDang/cimgui-go.
// DO NOT EDIT.


#pragma once

#include "cimgui/cimmarkdown.h"

#ifdef __cplusplus
extern "C" {
#endif

extern MarkdownImageData callbackMarkdownImageCallback(MarkdownLinkCallbackData data);

extern void callbackMarkdownLinkCallback(MarkdownLinkCallbackData data);

extern void callbackMarkdownTooltipCallback(MarkdownTooltipCallbackData data);

#ifdef __cplusplus
}
#endif