// Code generated by cmd/codegen from https://github.com/AllenDang/cimgui-go.
// DO NOT EDIT.

package imgui

// #include <stdlib.h>
// #include <memory.h>
// #include "extra_types.h"
// #include "cimmarkdown_wrapper.h"
// #include "cimmarkdown_callbacks.h"
import "C"

const mapName_MarkdownImageCallback = "MarkdownImageCallback"

type MarkdownImageCallback func(data MarkdownLinkCallbackData) MarkdownImageData

// export callbackMarkdownImageCallback
func callbackMarkdownImageCallback(data C.MarkdownLinkCallbackData) C.MarkdownImageData {
	callbackInterface, ok := callbackMap[mapName_MarkdownImageCallback]
	if !ok {
		panic("cimgui-go fatal error: Callback MarkdownImageCallback not found")
	}

	callbackFn, ok := callbackInterface.(MarkdownImageCallback)
	if !ok {
		panic("cimgui-go fatal error: Callback MarkdownImageCallback is not of proper type")
	}

	dataArg := *newMarkdownLinkCallbackDataFromC(func() *C.MarkdownLinkCallbackData { result := data; return &result }())

	callbackFn(dataArg)
}

func setMarkdownImageCallbackCallback(callback MarkdownImageCallback) {
	callbackMap[mapName_MarkdownImageCallback] = callback
}

const mapName_MarkdownLinkCallback = "MarkdownLinkCallback"

type MarkdownLinkCallback func(data MarkdownLinkCallbackData)

// export callbackMarkdownLinkCallback
func callbackMarkdownLinkCallback(data C.MarkdownLinkCallbackData) {
	callbackInterface, ok := callbackMap[mapName_MarkdownLinkCallback]
	if !ok {
		panic("cimgui-go fatal error: Callback MarkdownLinkCallback not found")
	}

	callbackFn, ok := callbackInterface.(MarkdownLinkCallback)
	if !ok {
		panic("cimgui-go fatal error: Callback MarkdownLinkCallback is not of proper type")
	}

	dataArg := *newMarkdownLinkCallbackDataFromC(func() *C.MarkdownLinkCallbackData { result := data; return &result }())

	callbackFn(dataArg)
}

func setMarkdownLinkCallbackCallback(callback MarkdownLinkCallback) {
	callbackMap[mapName_MarkdownLinkCallback] = callback
}

const mapName_MarkdownTooltipCallback = "MarkdownTooltipCallback"

type MarkdownTooltipCallback func(data MarkdownTooltipCallbackData)

// export callbackMarkdownTooltipCallback
func callbackMarkdownTooltipCallback(data C.MarkdownTooltipCallbackData) {
	callbackInterface, ok := callbackMap[mapName_MarkdownTooltipCallback]
	if !ok {
		panic("cimgui-go fatal error: Callback MarkdownTooltipCallback not found")
	}

	callbackFn, ok := callbackInterface.(MarkdownTooltipCallback)
	if !ok {
		panic("cimgui-go fatal error: Callback MarkdownTooltipCallback is not of proper type")
	}

	dataArg := *newMarkdownTooltipCallbackDataFromC(func() *C.MarkdownTooltipCallbackData { result := data; return &result }())

	callbackFn(dataArg)
}

func setMarkdownTooltipCallbackCallback(callback MarkdownTooltipCallback) {
	callbackMap[mapName_MarkdownTooltipCallback] = callback
}
