// Code generated by cmd/codegen from https://github.com/AllenDang/cimgui-go.
// DO NOT EDIT.

package imspinner

// original name: SpinnerTypeT
type SpinnerTypeT int32

const (
	estrainbow      SpinnerTypeT = 0
	estangle        SpinnerTypeT = 1
	estdots         SpinnerTypeT = 2
	estang          SpinnerTypeT = 3
	estvdots        SpinnerTypeT = 4
	estbounceball   SpinnerTypeT = 5
	esteclipse      SpinnerTypeT = 6
	estingyang      SpinnerTypeT = 7
	estbarchartsine SpinnerTypeT = 8
	estcount        SpinnerTypeT = 9
)

// original name: ease_mode
type easemode int32

const (
	eeasenone      easemode = 0
	eeaseinoutquad easemode = 1
	eeaseinoutexpo easemode = 2
	eeasespring    easemode = 3
	eeasegravity   easemode = 4
	eeaseinfinity  easemode = 5
	eeaseelastic   easemode = 6
	eeasesine      easemode = 7
)
