// Code generated by cmd/codegen from https://github.com/AllenDang/cimgui-go.
// DO NOT EDIT.

#pragma once


#include "../cwrappers/cimspinner.h"

#ifdef __cplusplus
extern "C" {
#endif

extern void wrap_ImSpinner_Spinner3SmuggleDots(const char* label,float radius,float thickness);
extern void wrap_ImSpinner_Spinner4Caleidospcope(const char* label,float radius,float thickness);
extern void wrap_ImSpinner_SpinnerAng(const char* label,float radius,float thickness);
extern void wrap_ImSpinner_SpinnerAng8(const char* label,float radius,float thickness);
extern void wrap_ImSpinner_SpinnerAngEclipse(const char* label,float radius,float thickness);
extern void wrap_ImSpinner_SpinnerAngMix(const char* label,float radius,float thickness);
extern void wrap_ImSpinner_SpinnerAngTriple(const char* label,float radius1,float radius2,float radius3,float thickness);
extern void wrap_ImSpinner_SpinnerAngTwin(const char* label,float radius1,float radius2,float thickness);
extern void wrap_ImSpinner_SpinnerArcFade(const char* label,float radius,float thickness);
extern void wrap_ImSpinner_SpinnerArcPolarFade(const char* label,float radius);
extern void wrap_ImSpinner_SpinnerArcPolarRadius(const char* label,float radius);
extern void wrap_ImSpinner_SpinnerArcRotation(const char* label,float radius,float thickness);
extern void wrap_ImSpinner_SpinnerArcWedges(const char* label,float radius);
extern void wrap_ImSpinner_SpinnerAsciiSymbolPoints(const char* label,const char* text,float radius,float thickness);
extern void wrap_ImSpinner_SpinnerAtom(const char* label,float radius,float thickness);
extern void wrap_ImSpinner_SpinnerBarChartAdvSine(const char* label,float radius,float thickness,const ImColor color,float speed);
extern void wrap_ImSpinner_SpinnerBarChartAdvSineFade(const char* label,float radius,float thickness,const ImColor color,float speed);
extern void wrap_ImSpinner_SpinnerBarChartRainbow(const char* label,float radius,float thickness,const ImColor color,float speed);
extern void wrap_ImSpinner_SpinnerBarChartSine(const char* label,float radius,float thickness,const ImColor color,float speed);
extern void wrap_ImSpinner_SpinnerBarsRotateFade(const char* label,float rmin,float rmax,float thickness);
extern void wrap_ImSpinner_SpinnerBarsScaleMiddle(const char* label,float w);
extern void wrap_ImSpinner_SpinnerBounceBall(const char* label,float radius,float thickness);
extern void wrap_ImSpinner_SpinnerBounceDots(const char* label,float radius,float thickness);
extern void wrap_ImSpinner_SpinnerCaleidoscope(const char* label,float radius,float thickness);
extern void wrap_ImSpinner_SpinnerCamera(const char* label,float radius,float thickness,LeafColor* leaf_color);
extern void wrap_ImSpinner_SpinnerCircleDrop(const char* label,float radius,float thickness,float thickness_drop);
extern void wrap_ImSpinner_SpinnerCircularLines(const char* label,float radius);
extern void wrap_ImSpinner_SpinnerCircularPoints(const char* label,float radius,float thickness);
extern void wrap_ImSpinner_SpinnerClock(const char* label,float radius,float thickness);
extern void wrap_ImSpinner_SpinnerCurvedCircle(const char* label,float radius,float thickness);
extern void wrap_ImSpinner_SpinnerDnaDots(const char* label,float radius,float thickness);
extern void wrap_ImSpinner_SpinnerDots(const char* label,float* nextdot,float radius,float thickness);
extern void wrap_ImSpinner_SpinnerDotsToBar(const char* label,float radius,float thickness,float offset_k);
extern void wrap_ImSpinner_SpinnerDotsToPoints(const char* label,float radius,float thickness,float offset_k);
extern void wrap_ImSpinner_SpinnerDoubleFadePulsar(const char* label,float radius,float noname1);
extern void wrap_ImSpinner_SpinnerFadeBars(const char* label,float w);
extern void wrap_ImSpinner_SpinnerFadeDots(const char* label,float radius,float thickness);
extern void wrap_ImSpinner_SpinnerFadePulsar(const char* label,float radius);
extern void wrap_ImSpinner_SpinnerFadePulsarSquare(const char* label,float radius);
extern void wrap_ImSpinner_SpinnerFadeTris(const char* label,float radius);
extern void wrap_ImSpinner_SpinnerFilledArcColor(const char* label,float radius);
extern void wrap_ImSpinner_SpinnerFilledArcFade(const char* label,float radius);
extern void wrap_ImSpinner_SpinnerFilledArcRing(const char* label,float radius,float thickness);
extern void wrap_ImSpinner_SpinnerFilling(const char* label,float radius,float thickness);
extern void wrap_ImSpinner_SpinnerFiveDots(const char* label,float radius,float thickness);
extern void wrap_ImSpinner_SpinnerFlowingGradient(const char* label,float radius,float thickness);
extern void wrap_ImSpinner_SpinnerFluid(const char* label,float radius,const ImColor color,float speed);
extern void wrap_ImSpinner_SpinnerFluidPoints(const char* label,float radius,float thickness,const ImColor color,float speed);
extern void wrap_ImSpinner_SpinnerGalaxyDots(const char* label,float radius,float thickness);
extern void wrap_ImSpinner_SpinnerGooeyBalls(const char* label,float radius,const ImColor color,float speed);
extern void wrap_ImSpinner_SpinnerHboDots(const char* label,float radius,float thickness);
extern void wrap_ImSpinner_SpinnerIncDots(const char* label,float radius,float thickness);
extern void wrap_ImSpinner_SpinnerIncFullDots(const char* label,float radius,float thickness);
extern void wrap_ImSpinner_SpinnerIncScaleDots(const char* label,float radius,float thickness);
extern void wrap_ImSpinner_SpinnerIngYang(const char* label,float radius,float thickness,bool reverse,float yang_detlta_r);
extern void wrap_ImSpinner_SpinnerLemniscate(const char* label,float radius,float thickness);
extern void wrap_ImSpinner_SpinnerLoadingRing(const char* label,float radius,float thickness);
extern void wrap_ImSpinner_SpinnerModCircle(const char* label,float radius,float thickness);
extern void wrap_ImSpinner_SpinnerMoonDots(const char* label,float radius,float thickness,const ImColor first,const ImColor second);
extern void wrap_ImSpinner_SpinnerMoonLine(const char* label,float radius,float thickness);
extern void wrap_ImSpinner_SpinnerMovingArcs(const char* label,float radius,float thickness);
extern void wrap_ImSpinner_SpinnerMovingDots(const char* label,float radius,float thickness);
extern void wrap_ImSpinner_SpinnerMultiFadeDots(const char* label,float radius,float thickness);
extern void wrap_ImSpinner_SpinnerOrionDots(const char* label,float radius,float thickness);
extern void wrap_ImSpinner_SpinnerPatternEclipse(const char* label,float radius,float thickness);
extern void wrap_ImSpinner_SpinnerPatternRings(const char* label,float radius,float thickness);
extern void wrap_ImSpinner_SpinnerPatternSphere(const char* label,float radius,float thickness);
extern void wrap_ImSpinner_SpinnerPointsArcBounce(const char* label,float radius,float thickness);
extern void wrap_ImSpinner_SpinnerPointsRoller(const char* label,float radius,float thickness);
extern void wrap_ImSpinner_SpinnerPointsShift(const char* label,float radius,float thickness);
extern void wrap_ImSpinner_SpinnerPulsar(const char* label,float radius,float thickness);
extern void wrap_ImSpinner_SpinnerPulsarBall(const char* label,float radius,float thickness);
extern void wrap_ImSpinner_SpinnerRainbow(const char* label,float radius,float thickness,const ImColor color,float speed);
extern void wrap_ImSpinner_SpinnerRainbowBalls(const char* label,float radius,float thickness,const ImColor color,float speed);
extern void wrap_ImSpinner_SpinnerRainbowCircle(const char* label,float radius,float thickness);
extern void wrap_ImSpinner_SpinnerRainbowMix(const char* label,float radius,float thickness,const ImColor color,float speed);
extern void wrap_ImSpinner_SpinnerRainbowShot(const char* label,float radius,float thickness,const ImColor color,float speed);
extern void wrap_ImSpinner_SpinnerRingSynchronous(const char* label,float radius,float thickness);
extern void wrap_ImSpinner_SpinnerRingWatermarks(const char* label,float radius,float thickness);
extern void wrap_ImSpinner_SpinnerRotateDots(const char* label,float radius,float thickness);
extern void wrap_ImSpinner_SpinnerRotateGear(const char* label,float radius,float thickness);
extern void wrap_ImSpinner_SpinnerRotateGooeyBalls(const char* label,float radius,float thickness,const ImColor color,float speed,int balls);
extern void wrap_ImSpinner_SpinnerRotateSegments(const char* label,float radius,float thickness);
extern void wrap_ImSpinner_SpinnerRotateSegmentsPulsar(const char* label,float radius,float thickness);
extern void wrap_ImSpinner_SpinnerRotateTriangles(const char* label,float radius,float thickness,const ImColor color,float speed,int tris);
extern void wrap_ImSpinner_SpinnerRotateWheel(const char* label,float radius,float thickness);
extern void wrap_ImSpinner_SpinnerRotatedAtom(const char* label,float radius,float thickness);
extern void wrap_ImSpinner_SpinnerRotatingHeart(const char* label,float radius,float thickness,const ImColor color,float speed);
extern void wrap_ImSpinner_SpinnerScaleBlocks(const char* label,float radius,float thickness,const ImColor color,float speed);
extern void wrap_ImSpinner_SpinnerScaleDots(const char* label,float radius,float thickness);
extern void wrap_ImSpinner_SpinnerSevenSegments(const char* label,const char* text,float radius,float thickness);
extern void wrap_ImSpinner_SpinnerSimpleArcFade(const char* label,float radius,float thickness);
extern void wrap_ImSpinner_SpinnerSinSquares(const char* label,float radius,float thickness,const ImColor color,float speed);
extern void wrap_ImSpinner_SpinnerSineArcs(const char* label,float radius,float thickness);
extern void wrap_ImSpinner_SpinnerSolarArcs(const char* label,float radius,float thickness);
extern void wrap_ImSpinner_SpinnerSolarBalls(const char* label,float radius,float thickness);
extern void wrap_ImSpinner_SpinnerSolarScaleBalls(const char* label,float radius,float thickness);
extern void wrap_ImSpinner_SpinnerSomeScaleDots(const char* label,float radius,float thickness);
extern void wrap_ImSpinner_SpinnerSpiral(const char* label,float radius,float thickness);
extern void wrap_ImSpinner_SpinnerSpiralEye(const char* label,float radius,float thickness);
extern void wrap_ImSpinner_SpinnerSplineAng(const char* label,float radius,float thickness);
extern void wrap_ImSpinner_SpinnerSquareLoading(const char* label,float radius,float thickness);
extern void wrap_ImSpinner_SpinnerSquareSpins(const char* label,float radius,float thickness);
extern void wrap_ImSpinner_SpinnerSquareStrokeFade(const char* label,float radius,float thickness);
extern void wrap_ImSpinner_SpinnerSquareStrokeFill(const char* label,float radius,float thickness);
extern void wrap_ImSpinner_SpinnerSquareStrokeLoading(const char* label,float radius,float thickness);
extern void wrap_ImSpinner_SpinnerSurroundedIndicator(const char* label,float radius,float thickness);
extern void wrap_ImSpinner_SpinnerSwingDots(const char* label,float radius,float thickness);
extern void wrap_ImSpinner_SpinnerTextFading(const char* label,const char* text,float radius,float fsize);
extern void wrap_ImSpinner_SpinnerThickToSin(const char* label,float radius,float thickness);
extern void wrap_ImSpinner_SpinnerThreeDots(const char* label,float radius,float thickness);
extern void wrap_ImSpinner_SpinnerThreeDotsStar(const char* label,float radius,float thickness);
extern void wrap_ImSpinner_SpinnerTopup(const char* label,float radius1,float radius2);
extern void wrap_ImSpinner_SpinnerTrianglesSelector(const char* label,float radius,float thickness);
extern void wrap_ImSpinner_SpinnerTrianglesShift(const char* label,float radius,float thickness);
extern void wrap_ImSpinner_SpinnerTwinAng(const char* label,float radius1,float radius2,float thickness);
extern void wrap_ImSpinner_SpinnerTwinAng180(const char* label,float radius1,float radius2,float thickness);
extern void wrap_ImSpinner_SpinnerTwinAng360(const char* label,float radius1,float radius2,float thickness);
extern void wrap_ImSpinner_SpinnerTwinBall(const char* label,float radius1,float radius2,float thickness,float b_thickness);
extern void wrap_ImSpinner_SpinnerTwinHboDots(const char* label,float radius,float thickness);
extern void wrap_ImSpinner_SpinnerTwinPulsar(const char* label,float radius,float thickness);
extern void wrap_ImSpinner_SpinnerVDots(const char* label,float radius,float thickness);
extern void wrap_ImSpinner_SpinnerWaveDots(const char* label,float radius,float thickness);
extern void wrap_ImSpinner_SpinnerWifiIndicator(const char* label,float radius,float thickness);
extern void wrap_ImSpinner_SpinnerZipDots(const char* label,float radius,float thickness);
extern float wrap_ImSpinner_damped_spring(float mass,float stiffness,float damping,float time);
extern float wrap_ImSpinner_damped_trifolium(float limtime);

#ifdef __cplusplus
}
#endif
