// Code generated by cmd/codegen from https://github.com/AllenDang/cimgui-go.
// DO NOT EDIT.


#include <string.h>
#include "cimcte_wrapper.h"
#include "cimcte_structs_accessor.h"

void wrap_Coordinates_SetMLine(Coordinates *CoordinatesPtr, int v) { CoordinatesPtr->mLine = v; }
int wrap_Coordinates_GetMLine(Coordinates *self) { return self->mLine; }
void wrap_Coordinates_SetMColumn(Coordinates *CoordinatesPtr, int v) { CoordinatesPtr->mColumn = v; }
int wrap_Coordinates_GetMColumn(Coordinates *self) { return self->mColumn; }
