// Code generated by cmd/codegen from https://github.com/AllenDang/cimgui-go.
// DO NOT EDIT.

package imguiColorTextEdit

// original name: SelectionMode_
type SelectionMode int32

const (
	Normal SelectionMode = 0
	Word   SelectionMode = 1
	Line   SelectionMode = 2
)
