// Code generated by cmd/codegen from https://github.com/AllenDang/cimgui-go.
// DO NOT EDIT.

package imguiColorTextEdit

import (
	"github.com/AllenDang/cimgui-go/datautils"
)

// #include "../imgui/extra_types.h"
// #include "cimcte_structs_accessor.h"
// #include "cimcte_wrapper.h"
import "C"

func (self Coordinates) SetMLine(v int32) {
	selfArg, selfFin := self.Handle()
	defer selfFin()
	C.wrap_Coordinates_SetMLine(selfArg, C.int(v))
}

func (self *Coordinates) MLine() int32 {
	selfArg, selfFin := self.Handle()

	defer func() {
		selfFin()
	}()
	return int32(C.wrap_Coordinates_GetMLine(datautils.ConvertCTypes[*C.Coordinates](selfArg)))
}

func (self Coordinates) SetMColumn(v int32) {
	selfArg, selfFin := self.Handle()
	defer selfFin()
	C.wrap_Coordinates_SetMColumn(selfArg, C.int(v))
}

func (self *Coordinates) MColumn() int32 {
	selfArg, selfFin := self.Handle()

	defer func() {
		selfFin()
	}()
	return int32(C.wrap_Coordinates_GetMColumn(datautils.ConvertCTypes[*C.Coordinates](selfArg)))
}
