// Code generated by cmd/codegen from https://github.com/AllenDang/cimgui-go.
// DO NOT EDIT.

#pragma once

#include "cimcte_wrapper.h"

#ifdef __cplusplus
extern "C" {
#endif

extern void wrap_Coordinates_SetMLine(Coordinates *CoordinatesPtr, int v);
extern int wrap_Coordinates_GetMLine(Coordinates *self);
extern void wrap_Coordinates_SetMColumn(Coordinates *CoordinatesPtr, int v);
extern int wrap_Coordinates_GetMColumn(Coordinates *self);

#ifdef __cplusplus
}
#endif
