// Code generated by cmd/codegen from https://github.com/AllenDang/cimgui-go.
// DO NOT EDIT.

package immarkdown

import (
	"unsafe"

	"github.com/AllenDang/cimgui-go/imgui"
	"github.com/AllenDang/cimgui-go/internal"
)

// #include "../imgui/extra_types.h"
// #include "cimmarkdown_structs_accessor.h"
// #include "cimmarkdown_wrapper.h"
// #include "stdlib.h"
import "C"

func IsCharInsideWord(c_ rune) bool {
	return C.IsCharInsideWord(C.char(c_)) == C.bool(true)
}

func Markdown(markdown_ string, markdownLength_ uint64, mdConfig_ MarkdownConfig) {
	markdown_Arg, markdown_Fin := internal.WrapString[C.char](markdown_)
	mdConfig_Arg, mdConfig_Fin := mdConfig_.C()
	C.Markdown(markdown_Arg, C.xulong(markdownLength_), internal.ReinterpretCast[C.MarkdownConfig](mdConfig_Arg))

	markdown_Fin()
	mdConfig_Fin()
}

func RenderLine(markdown_ string, line_ *Line, textRegion_ *TextRegion, mdConfig_ MarkdownConfig) {
	markdown_Arg, markdown_Fin := internal.WrapString[C.char](markdown_)
	line_Arg, line_Fin := line_.Handle()
	textRegion_Arg, textRegion_Fin := textRegion_.Handle()
	mdConfig_Arg, mdConfig_Fin := mdConfig_.C()
	C.RenderLine(markdown_Arg, internal.ReinterpretCast[*C.Line](line_Arg), internal.ReinterpretCast[*C.TextRegion](textRegion_Arg), internal.ReinterpretCast[C.MarkdownConfig](mdConfig_Arg))

	markdown_Fin()
	line_Fin()
	textRegion_Fin()
	mdConfig_Fin()
}

func RenderLinkText(self *TextRegion, text_ string, link_ Link, markdown_ string, mdConfig_ MarkdownConfig, linkHoverStart_ []string) bool {
	selfArg, selfFin := self.Handle()
	text_Arg, text_Fin := internal.WrapString[C.char](text_)
	link_Arg, link_Fin := link_.C()
	markdown_Arg, markdown_Fin := internal.WrapString[C.char](markdown_)
	mdConfig_Arg, mdConfig_Fin := mdConfig_.C()
	linkHoverStart_Arg, linkHoverStart_Fin := internal.WrapStringList[C.char](linkHoverStart_)

	defer func() {
		selfFin()
		text_Fin()
		link_Fin()
		markdown_Fin()
		mdConfig_Fin()
		linkHoverStart_Fin()
	}()
	return C.wrap_RenderLinkText(internal.ReinterpretCast[*C.TextRegion](selfArg), text_Arg, internal.ReinterpretCast[C.Link](link_Arg), markdown_Arg, internal.ReinterpretCast[C.MarkdownConfig](mdConfig_Arg), linkHoverStart_Arg) == C.bool(true)
}

// RenderLinkTextWrappedV parameter default value hint:
// bIndentToHere_: false
func RenderLinkTextWrappedV(self *TextRegion, text_ string, link_ Link, markdown_ string, mdConfig_ MarkdownConfig, linkHoverStart_ []string, bIndentToHere_ bool) {
	selfArg, selfFin := self.Handle()
	text_Arg, text_Fin := internal.WrapString[C.char](text_)
	link_Arg, link_Fin := link_.C()
	markdown_Arg, markdown_Fin := internal.WrapString[C.char](markdown_)
	mdConfig_Arg, mdConfig_Fin := mdConfig_.C()
	linkHoverStart_Arg, linkHoverStart_Fin := internal.WrapStringList[C.char](linkHoverStart_)
	C.wrap_RenderLinkTextWrappedV(internal.ReinterpretCast[*C.TextRegion](selfArg), text_Arg, internal.ReinterpretCast[C.Link](link_Arg), markdown_Arg, internal.ReinterpretCast[C.MarkdownConfig](mdConfig_Arg), linkHoverStart_Arg, C.bool(bIndentToHere_))

	selfFin()
	text_Fin()
	link_Fin()
	markdown_Fin()
	mdConfig_Fin()
	linkHoverStart_Fin()
}

func RenderListTextWrapped(self *TextRegion, text_ string) {
	selfArg, selfFin := self.Handle()
	text_Arg, text_Fin := internal.WrapString[C.char](text_)
	C.wrap_RenderListTextWrapped(internal.ReinterpretCast[*C.TextRegion](selfArg), text_Arg)

	selfFin()
	text_Fin()
}

// RenderTextWrappedV parameter default value hint:
// bIndentToHere_: false
func RenderTextWrappedV(self *TextRegion, text_ string, bIndentToHere_ bool) {
	selfArg, selfFin := self.Handle()
	text_Arg, text_Fin := internal.WrapString[C.char](text_)
	C.wrap_RenderTextWrappedV(internal.ReinterpretCast[*C.TextRegion](selfArg), text_Arg, C.bool(bIndentToHere_))

	selfFin()
	text_Fin()
}

func ResetIndent(self *TextRegion) {
	selfArg, selfFin := self.Handle()
	C.ResetIndent(internal.ReinterpretCast[*C.TextRegion](selfArg))

	selfFin()
}

func NewTextRegion() *TextRegion {
	return NewTextRegionFromC(C.TextRegion_TextRegion())
}

func (self *TextRegion) Destroy() {
	selfArg, selfFin := self.Handle()
	C.TextRegion_destroy(internal.ReinterpretCast[*C.TextRegion](selfArg))

	selfFin()
}

func UnderLine(col_ imgui.Color) {
	C.UnderLine(internal.ReinterpretCast[C.ImColor](col_.ToC()))
}

func RenderLinkTextWrapped(self *TextRegion, text_ string, link_ Link, markdown_ string, mdConfig_ MarkdownConfig, linkHoverStart_ []string) {
	selfArg, selfFin := self.Handle()
	text_Arg, text_Fin := internal.WrapString[C.char](text_)
	link_Arg, link_Fin := link_.C()
	markdown_Arg, markdown_Fin := internal.WrapString[C.char](markdown_)
	mdConfig_Arg, mdConfig_Fin := mdConfig_.C()
	linkHoverStart_Arg, linkHoverStart_Fin := internal.WrapStringList[C.char](linkHoverStart_)
	C.wrap_RenderLinkTextWrapped(internal.ReinterpretCast[*C.TextRegion](selfArg), text_Arg, internal.ReinterpretCast[C.Link](link_Arg), markdown_Arg, internal.ReinterpretCast[C.MarkdownConfig](mdConfig_Arg), linkHoverStart_Arg)

	selfFin()
	text_Fin()
	link_Fin()
	markdown_Fin()
	mdConfig_Fin()
	linkHoverStart_Fin()
}

func RenderTextWrapped(self *TextRegion, text_ string) {
	selfArg, selfFin := self.Handle()
	text_Arg, text_Fin := internal.WrapString[C.char](text_)
	C.wrap_RenderTextWrapped(internal.ReinterpretCast[*C.TextRegion](selfArg), text_Arg)

	selfFin()
	text_Fin()
}

// Emphasis_SetState sets value of Emphasis.state
func (self Emphasis) SetState(v EmphasisState) {
	selfArg, selfFin := self.Handle()
	defer selfFin()
	C.wrap_Emphasis_SetState(selfArg, C.EmphasisState(v))
}

// Emphasis_GetState returns value of Emphasis.state
func (self *Emphasis) State() EmphasisState {
	selfArg, selfFin := self.Handle()

	defer func() {
		selfFin()
	}()
	return EmphasisState(C.wrap_Emphasis_GetState(internal.ReinterpretCast[*C.Emphasis](selfArg)))
}

// Emphasis_SetText sets value of Emphasis.text
func (self Emphasis) SetText(v TextBlock) {
	vArg, _ := v.C()

	selfArg, selfFin := self.Handle()
	defer selfFin()
	C.wrap_Emphasis_SetText(selfArg, internal.ReinterpretCast[C.TextBlock](vArg))
}

// Emphasis_GetText returns value of Emphasis.text
func (self *Emphasis) Text() TextBlock {
	selfArg, selfFin := self.Handle()

	defer func() {
		selfFin()
	}()
	return *NewTextBlockFromC(func() *C.TextBlock {
		result := C.wrap_Emphasis_GetText(internal.ReinterpretCast[*C.Emphasis](selfArg))
		return &result
	}())
}

// Emphasis_SetSym sets value of Emphasis.sym
func (self Emphasis) SetSym(v rune) {
	selfArg, selfFin := self.Handle()
	defer selfFin()
	C.wrap_Emphasis_SetSym(selfArg, C.char(v))
}

// Emphasis_GetSym returns value of Emphasis.sym
func (self *Emphasis) Sym() rune {
	selfArg, selfFin := self.Handle()

	defer func() {
		selfFin()
	}()
	return rune(C.wrap_Emphasis_GetSym(internal.ReinterpretCast[*C.Emphasis](selfArg)))
}

// Line_SetIsHeading sets value of Line.isHeading
func (self Line) SetIsHeading(v bool) {
	selfArg, selfFin := self.Handle()
	defer selfFin()
	C.wrap_Line_SetIsHeading(selfArg, C.bool(v))
}

// Line_GetIsHeading returns value of Line.isHeading
func (self *Line) IsHeading() bool {
	selfArg, selfFin := self.Handle()

	defer func() {
		selfFin()
	}()
	return C.wrap_Line_GetIsHeading(internal.ReinterpretCast[*C.Line](selfArg)) == C.bool(true)
}

// Line_SetIsEmphasis sets value of Line.isEmphasis
func (self Line) SetIsEmphasis(v bool) {
	selfArg, selfFin := self.Handle()
	defer selfFin()
	C.wrap_Line_SetIsEmphasis(selfArg, C.bool(v))
}

// Line_GetIsEmphasis returns value of Line.isEmphasis
func (self *Line) IsEmphasis() bool {
	selfArg, selfFin := self.Handle()

	defer func() {
		selfFin()
	}()
	return C.wrap_Line_GetIsEmphasis(internal.ReinterpretCast[*C.Line](selfArg)) == C.bool(true)
}

// Line_SetIsUnorderedListStart sets value of Line.isUnorderedListStart
func (self Line) SetIsUnorderedListStart(v bool) {
	selfArg, selfFin := self.Handle()
	defer selfFin()
	C.wrap_Line_SetIsUnorderedListStart(selfArg, C.bool(v))
}

// Line_GetIsUnorderedListStart returns value of Line.isUnorderedListStart
func (self *Line) IsUnorderedListStart() bool {
	selfArg, selfFin := self.Handle()

	defer func() {
		selfFin()
	}()
	return C.wrap_Line_GetIsUnorderedListStart(internal.ReinterpretCast[*C.Line](selfArg)) == C.bool(true)
}

// Line_SetIsLeadingSpace sets value of Line.isLeadingSpace
func (self Line) SetIsLeadingSpace(v bool) {
	selfArg, selfFin := self.Handle()
	defer selfFin()
	C.wrap_Line_SetIsLeadingSpace(selfArg, C.bool(v))
}

// Line_GetIsLeadingSpace returns value of Line.isLeadingSpace
func (self *Line) IsLeadingSpace() bool {
	selfArg, selfFin := self.Handle()

	defer func() {
		selfFin()
	}()
	return C.wrap_Line_GetIsLeadingSpace(internal.ReinterpretCast[*C.Line](selfArg)) == C.bool(true)
}

// Line_SetLeadSpaceCount sets value of Line.leadSpaceCount
func (self Line) SetLeadSpaceCount(v int32) {
	selfArg, selfFin := self.Handle()
	defer selfFin()
	C.wrap_Line_SetLeadSpaceCount(selfArg, C.int(v))
}

// Line_GetLeadSpaceCount returns value of Line.leadSpaceCount
func (self *Line) LeadSpaceCount() int32 {
	selfArg, selfFin := self.Handle()

	defer func() {
		selfFin()
	}()
	return int32(C.wrap_Line_GetLeadSpaceCount(internal.ReinterpretCast[*C.Line](selfArg)))
}

// Line_SetHeadingCount sets value of Line.headingCount
func (self Line) SetHeadingCount(v int32) {
	selfArg, selfFin := self.Handle()
	defer selfFin()
	C.wrap_Line_SetHeadingCount(selfArg, C.int(v))
}

// Line_GetHeadingCount returns value of Line.headingCount
func (self *Line) HeadingCount() int32 {
	selfArg, selfFin := self.Handle()

	defer func() {
		selfFin()
	}()
	return int32(C.wrap_Line_GetHeadingCount(internal.ReinterpretCast[*C.Line](selfArg)))
}

// Line_SetEmphasisCount sets value of Line.emphasisCount
func (self Line) SetEmphasisCount(v int32) {
	selfArg, selfFin := self.Handle()
	defer selfFin()
	C.wrap_Line_SetEmphasisCount(selfArg, C.int(v))
}

// Line_GetEmphasisCount returns value of Line.emphasisCount
func (self *Line) EmphasisCount() int32 {
	selfArg, selfFin := self.Handle()

	defer func() {
		selfFin()
	}()
	return int32(C.wrap_Line_GetEmphasisCount(internal.ReinterpretCast[*C.Line](selfArg)))
}

// Line_SetLineStart sets value of Line.lineStart
func (self Line) SetLineStart(v int32) {
	selfArg, selfFin := self.Handle()
	defer selfFin()
	C.wrap_Line_SetLineStart(selfArg, C.int(v))
}

// Line_GetLineStart returns value of Line.lineStart
func (self *Line) LineStart() int32 {
	selfArg, selfFin := self.Handle()

	defer func() {
		selfFin()
	}()
	return int32(C.wrap_Line_GetLineStart(internal.ReinterpretCast[*C.Line](selfArg)))
}

// Line_SetLineEnd sets value of Line.lineEnd
func (self Line) SetLineEnd(v int32) {
	selfArg, selfFin := self.Handle()
	defer selfFin()
	C.wrap_Line_SetLineEnd(selfArg, C.int(v))
}

// Line_GetLineEnd returns value of Line.lineEnd
func (self *Line) LineEnd() int32 {
	selfArg, selfFin := self.Handle()

	defer func() {
		selfFin()
	}()
	return int32(C.wrap_Line_GetLineEnd(internal.ReinterpretCast[*C.Line](selfArg)))
}

// Line_SetLastRenderPosition sets value of Line.lastRenderPosition
func (self Line) SetLastRenderPosition(v int32) {
	selfArg, selfFin := self.Handle()
	defer selfFin()
	C.wrap_Line_SetLastRenderPosition(selfArg, C.int(v))
}

// Line_GetLastRenderPosition returns value of Line.lastRenderPosition
func (self *Line) LastRenderPosition() int32 {
	selfArg, selfFin := self.Handle()

	defer func() {
		selfFin()
	}()
	return int32(C.wrap_Line_GetLastRenderPosition(internal.ReinterpretCast[*C.Line](selfArg)))
}

// Link_SetState sets value of Link.state
func (self Link) SetState(v LinkState) {
	selfArg, selfFin := self.Handle()
	defer selfFin()
	C.wrap_Link_SetState(selfArg, C.LinkState(v))
}

// Link_GetState returns value of Link.state
func (self *Link) State() LinkState {
	selfArg, selfFin := self.Handle()

	defer func() {
		selfFin()
	}()
	return LinkState(C.wrap_Link_GetState(internal.ReinterpretCast[*C.Link](selfArg)))
}

// Link_SetText sets value of Link.text
func (self Link) SetText(v TextBlock) {
	vArg, _ := v.C()

	selfArg, selfFin := self.Handle()
	defer selfFin()
	C.wrap_Link_SetText(selfArg, internal.ReinterpretCast[C.TextBlock](vArg))
}

// Link_GetText returns value of Link.text
func (self *Link) Text() TextBlock {
	selfArg, selfFin := self.Handle()

	defer func() {
		selfFin()
	}()
	return *NewTextBlockFromC(func() *C.TextBlock {
		result := C.wrap_Link_GetText(internal.ReinterpretCast[*C.Link](selfArg))
		return &result
	}())
}

// Link_SetUrl sets value of Link.url
func (self Link) SetUrl(v TextBlock) {
	vArg, _ := v.C()

	selfArg, selfFin := self.Handle()
	defer selfFin()
	C.wrap_Link_SetUrl(selfArg, internal.ReinterpretCast[C.TextBlock](vArg))
}

// Link_GetUrl returns value of Link.url
func (self *Link) Url() TextBlock {
	selfArg, selfFin := self.Handle()

	defer func() {
		selfFin()
	}()
	return *NewTextBlockFromC(func() *C.TextBlock {
		result := C.wrap_Link_GetUrl(internal.ReinterpretCast[*C.Link](selfArg))
		return &result
	}())
}

// Link_SetIsImage sets value of Link.isImage
func (self Link) SetIsImage(v bool) {
	selfArg, selfFin := self.Handle()
	defer selfFin()
	C.wrap_Link_SetIsImage(selfArg, C.bool(v))
}

// Link_GetIsImage returns value of Link.isImage
func (self *Link) IsImage() bool {
	selfArg, selfFin := self.Handle()

	defer func() {
		selfFin()
	}()
	return C.wrap_Link_GetIsImage(internal.ReinterpretCast[*C.Link](selfArg)) == C.bool(true)
}

// Link_SetNum_brackets_open sets value of Link.num_brackets_open
func (self Link) SetNumbracketsopen(v int32) {
	selfArg, selfFin := self.Handle()
	defer selfFin()
	C.wrap_Link_SetNum_brackets_open(selfArg, C.int(v))
}

// Link_GetNum_brackets_open returns value of Link.num_brackets_open
func (self *Link) Numbracketsopen() int32 {
	selfArg, selfFin := self.Handle()

	defer func() {
		selfFin()
	}()
	return int32(C.wrap_Link_GetNum_brackets_open(internal.ReinterpretCast[*C.Link](selfArg)))
}

// MarkdownConfig_SetLinkIcon sets value of MarkdownConfig.linkIcon
func (self MarkdownConfig) SetLinkIcon(v string) {
	vArg, _ := internal.WrapString[C.char](v)

	selfArg, selfFin := self.Handle()
	defer selfFin()
	C.wrap_MarkdownConfig_SetLinkIcon(selfArg, vArg)
}

// MarkdownConfig_GetLinkIcon returns value of MarkdownConfig.linkIcon
func (self *MarkdownConfig) LinkIcon() string {
	selfArg, selfFin := self.Handle()

	defer func() {
		selfFin()
	}()
	return func() string {
		result := C.wrap_MarkdownConfig_GetLinkIcon(internal.ReinterpretCast[*C.MarkdownConfig](selfArg))
		defer C.free(unsafe.Pointer(result))
		return C.GoString(result)
	}()
}

// MarkdownConfig_SetHeadingFormats sets value of MarkdownConfig.headingFormats[NUMHEADINGS]
func (self MarkdownConfig) SetHeadingFormats(v *[3]MarkdownHeadingFormat) {
	vArg := make([]C.MarkdownHeadingFormat, len(v))
	for i, vV := range v {
		vVArg, _ := vV.C()
		vArg[i] = internal.ReinterpretCast[C.MarkdownHeadingFormat](vVArg)
	}

	selfArg, selfFin := self.Handle()
	defer selfFin()
	C.wrap_MarkdownConfig_SetHeadingFormats(selfArg, (*C.MarkdownHeadingFormat)(&vArg[0]))

	for i, vV := range vArg {
		(*v)[i] = *NewMarkdownHeadingFormatFromC(func() *C.MarkdownHeadingFormat { result := vV; return &result }())
	}
}

// MarkdownConfig_GetHeadingFormats returns value of MarkdownConfig.headingFormats[NUMHEADINGS]
func (self *MarkdownConfig) HeadingFormats() [3]MarkdownHeadingFormat {
	selfArg, selfFin := self.Handle()

	defer func() {
		selfFin()
	}()
	return func() [3]MarkdownHeadingFormat {
		result := [3]MarkdownHeadingFormat{}
		resultMirr := C.wrap_MarkdownConfig_GetHeadingFormats(internal.ReinterpretCast[*C.MarkdownConfig](selfArg))
		for i := range result {
			result[i] = *NewMarkdownHeadingFormatFromC(func() *C.MarkdownHeadingFormat {
				result := C.cimmarkdown_MarkdownHeadingFormat_GetAtIdx(resultMirr, C.int(i))
				return &result
			}())
		}

		return result
	}()
}

// MarkdownConfig_SetUserData sets value of MarkdownConfig.userData
func (self MarkdownConfig) SetUserData(v uintptr) {
	selfArg, selfFin := self.Handle()
	defer selfFin()
	C.wrap_MarkdownConfig_SetUserData(selfArg, C.uintptr_t(v))
}

// MarkdownConfig_GetUserData returns value of MarkdownConfig.userData
func (self *MarkdownConfig) UserData() uintptr {
	selfArg, selfFin := self.Handle()

	defer func() {
		selfFin()
	}()
	return uintptr(C.wrap_MarkdownConfig_GetUserData(internal.ReinterpretCast[*C.MarkdownConfig](selfArg)))
}

// MarkdownFormatInfo_SetType sets value of MarkdownFormatInfo.type
func (self MarkdownFormatInfo) SetType(v MarkdownFormatType) {
	selfArg, selfFin := self.Handle()
	defer selfFin()
	C.wrap_MarkdownFormatInfo_SetType(selfArg, C.MarkdownFormatType(v))
}

// MarkdownFormatInfo_GetType returns value of MarkdownFormatInfo.type
func (self *MarkdownFormatInfo) Type() MarkdownFormatType {
	selfArg, selfFin := self.Handle()

	defer func() {
		selfFin()
	}()
	return MarkdownFormatType(C.wrap_MarkdownFormatInfo_GetType(internal.ReinterpretCast[*C.MarkdownFormatInfo](selfArg)))
}

// MarkdownFormatInfo_SetLevel sets value of MarkdownFormatInfo.level
func (self MarkdownFormatInfo) SetLevel(v int32) {
	selfArg, selfFin := self.Handle()
	defer selfFin()
	C.wrap_MarkdownFormatInfo_SetLevel(selfArg, C.int32_t(v))
}

// MarkdownFormatInfo_GetLevel returns value of MarkdownFormatInfo.level
func (self *MarkdownFormatInfo) Level() int32 {
	selfArg, selfFin := self.Handle()

	defer func() {
		selfFin()
	}()
	return int32(C.wrap_MarkdownFormatInfo_GetLevel(internal.ReinterpretCast[*C.MarkdownFormatInfo](selfArg)))
}

// MarkdownFormatInfo_SetItemHovered sets value of MarkdownFormatInfo.itemHovered
func (self MarkdownFormatInfo) SetItemHovered(v bool) {
	selfArg, selfFin := self.Handle()
	defer selfFin()
	C.wrap_MarkdownFormatInfo_SetItemHovered(selfArg, C.bool(v))
}

// MarkdownFormatInfo_GetItemHovered returns value of MarkdownFormatInfo.itemHovered
func (self *MarkdownFormatInfo) ItemHovered() bool {
	selfArg, selfFin := self.Handle()

	defer func() {
		selfFin()
	}()
	return C.wrap_MarkdownFormatInfo_GetItemHovered(internal.ReinterpretCast[*C.MarkdownFormatInfo](selfArg)) == C.bool(true)
}

// MarkdownFormatInfo_SetConfig sets value of MarkdownFormatInfo.config
func (self MarkdownFormatInfo) SetConfig(v *MarkdownConfig) {
	vArg, _ := v.Handle()

	selfArg, selfFin := self.Handle()
	defer selfFin()
	C.wrap_MarkdownFormatInfo_SetConfig(selfArg, internal.ReinterpretCast[*C.MarkdownConfig](vArg))
}

// MarkdownFormatInfo_GetConfig returns value of MarkdownFormatInfo.config
func (self *MarkdownFormatInfo) Config() *MarkdownConfig {
	selfArg, selfFin := self.Handle()

	defer func() {
		selfFin()
	}()
	return NewMarkdownConfigFromC(C.wrap_MarkdownFormatInfo_GetConfig(internal.ReinterpretCast[*C.MarkdownFormatInfo](selfArg)))
}

// MarkdownHeadingFormat_SetFont sets value of MarkdownHeadingFormat.font
func (self MarkdownHeadingFormat) SetFont(v *imgui.Font) {
	vArg, _ := v.Handle()

	selfArg, selfFin := self.Handle()
	defer selfFin()
	C.wrap_MarkdownHeadingFormat_SetFont(selfArg, internal.ReinterpretCast[*C.ImFont](vArg))
}

// MarkdownHeadingFormat_GetFont returns value of MarkdownHeadingFormat.font
func (self *MarkdownHeadingFormat) Font() *imgui.Font {
	selfArg, selfFin := self.Handle()

	defer func() {
		selfFin()
	}()
	return imgui.NewFontFromC(C.wrap_MarkdownHeadingFormat_GetFont(internal.ReinterpretCast[*C.MarkdownHeadingFormat](selfArg)))
}

// MarkdownHeadingFormat_SetSeparator sets value of MarkdownHeadingFormat.separator
func (self MarkdownHeadingFormat) SetSeparator(v bool) {
	selfArg, selfFin := self.Handle()
	defer selfFin()
	C.wrap_MarkdownHeadingFormat_SetSeparator(selfArg, C.bool(v))
}

// MarkdownHeadingFormat_GetSeparator returns value of MarkdownHeadingFormat.separator
func (self *MarkdownHeadingFormat) Separator() bool {
	selfArg, selfFin := self.Handle()

	defer func() {
		selfFin()
	}()
	return C.wrap_MarkdownHeadingFormat_GetSeparator(internal.ReinterpretCast[*C.MarkdownHeadingFormat](selfArg)) == C.bool(true)
}

// MarkdownImageData_SetIsValid sets value of MarkdownImageData.isValid
func (self MarkdownImageData) SetIsValid(v bool) {
	selfArg, selfFin := self.Handle()
	defer selfFin()
	C.wrap_MarkdownImageData_SetIsValid(selfArg, C.bool(v))
}

// MarkdownImageData_GetIsValid returns value of MarkdownImageData.isValid
func (self *MarkdownImageData) IsValid() bool {
	selfArg, selfFin := self.Handle()

	defer func() {
		selfFin()
	}()
	return C.wrap_MarkdownImageData_GetIsValid(internal.ReinterpretCast[*C.MarkdownImageData](selfArg)) == C.bool(true)
}

// MarkdownImageData_SetUseLinkCallback sets value of MarkdownImageData.useLinkCallback
func (self MarkdownImageData) SetUseLinkCallback(v bool) {
	selfArg, selfFin := self.Handle()
	defer selfFin()
	C.wrap_MarkdownImageData_SetUseLinkCallback(selfArg, C.bool(v))
}

// MarkdownImageData_GetUseLinkCallback returns value of MarkdownImageData.useLinkCallback
func (self *MarkdownImageData) UseLinkCallback() bool {
	selfArg, selfFin := self.Handle()

	defer func() {
		selfFin()
	}()
	return C.wrap_MarkdownImageData_GetUseLinkCallback(internal.ReinterpretCast[*C.MarkdownImageData](selfArg)) == C.bool(true)
}

// MarkdownImageData_SetUser_texture_id sets value of MarkdownImageData.user_texture_id
func (self MarkdownImageData) SetUsertextureid(v imgui.TextureID) {
	vArg, _ := v.C()

	selfArg, selfFin := self.Handle()
	defer selfFin()
	C.wrap_MarkdownImageData_SetUser_texture_id(selfArg, internal.ReinterpretCast[C.ImTextureID](vArg))
}

// MarkdownImageData_GetUser_texture_id returns value of MarkdownImageData.user_texture_id
func (self *MarkdownImageData) Usertextureid() imgui.TextureID {
	selfArg, selfFin := self.Handle()

	defer func() {
		selfFin()
	}()
	return *imgui.NewTextureIDFromC(func() *C.ImTextureID {
		result := C.wrap_MarkdownImageData_GetUser_texture_id(internal.ReinterpretCast[*C.MarkdownImageData](selfArg))
		return &result
	}())
}

// MarkdownImageData_SetSize sets value of MarkdownImageData.size
func (self MarkdownImageData) SetSize(v imgui.Vec2) {
	selfArg, selfFin := self.Handle()
	defer selfFin()
	C.wrap_MarkdownImageData_SetSize(selfArg, internal.ReinterpretCast[C.ImVec2](v.ToC()))
}

// MarkdownImageData_GetSize returns value of MarkdownImageData.size
func (self *MarkdownImageData) Size() imgui.Vec2 {
	selfArg, selfFin := self.Handle()

	defer func() {
		selfFin()
	}()
	return func() imgui.Vec2 {
		out := C.wrap_MarkdownImageData_GetSize(internal.ReinterpretCast[*C.MarkdownImageData](selfArg))
		return *(&imgui.Vec2{}).FromC(unsafe.Pointer(&out))
	}()
}

// MarkdownImageData_SetUv0 sets value of MarkdownImageData.uv0
func (self MarkdownImageData) SetUv0(v imgui.Vec2) {
	selfArg, selfFin := self.Handle()
	defer selfFin()
	C.wrap_MarkdownImageData_SetUv0(selfArg, internal.ReinterpretCast[C.ImVec2](v.ToC()))
}

// MarkdownImageData_GetUv0 returns value of MarkdownImageData.uv0
func (self *MarkdownImageData) Uv0() imgui.Vec2 {
	selfArg, selfFin := self.Handle()

	defer func() {
		selfFin()
	}()
	return func() imgui.Vec2 {
		out := C.wrap_MarkdownImageData_GetUv0(internal.ReinterpretCast[*C.MarkdownImageData](selfArg))
		return *(&imgui.Vec2{}).FromC(unsafe.Pointer(&out))
	}()
}

// MarkdownImageData_SetUv1 sets value of MarkdownImageData.uv1
func (self MarkdownImageData) SetUv1(v imgui.Vec2) {
	selfArg, selfFin := self.Handle()
	defer selfFin()
	C.wrap_MarkdownImageData_SetUv1(selfArg, internal.ReinterpretCast[C.ImVec2](v.ToC()))
}

// MarkdownImageData_GetUv1 returns value of MarkdownImageData.uv1
func (self *MarkdownImageData) Uv1() imgui.Vec2 {
	selfArg, selfFin := self.Handle()

	defer func() {
		selfFin()
	}()
	return func() imgui.Vec2 {
		out := C.wrap_MarkdownImageData_GetUv1(internal.ReinterpretCast[*C.MarkdownImageData](selfArg))
		return *(&imgui.Vec2{}).FromC(unsafe.Pointer(&out))
	}()
}

// MarkdownImageData_SetTint_col sets value of MarkdownImageData.tint_col
func (self MarkdownImageData) SetTintcol(v imgui.Vec4) {
	selfArg, selfFin := self.Handle()
	defer selfFin()
	C.wrap_MarkdownImageData_SetTint_col(selfArg, internal.ReinterpretCast[C.ImVec4](v.ToC()))
}

// MarkdownImageData_GetTint_col returns value of MarkdownImageData.tint_col
func (self *MarkdownImageData) Tintcol() imgui.Vec4 {
	selfArg, selfFin := self.Handle()

	defer func() {
		selfFin()
	}()
	return func() imgui.Vec4 {
		out := C.wrap_MarkdownImageData_GetTint_col(internal.ReinterpretCast[*C.MarkdownImageData](selfArg))
		return *(&imgui.Vec4{}).FromC(unsafe.Pointer(&out))
	}()
}

// MarkdownImageData_SetBorder_col sets value of MarkdownImageData.border_col
func (self MarkdownImageData) SetBordercol(v imgui.Vec4) {
	selfArg, selfFin := self.Handle()
	defer selfFin()
	C.wrap_MarkdownImageData_SetBorder_col(selfArg, internal.ReinterpretCast[C.ImVec4](v.ToC()))
}

// MarkdownImageData_GetBorder_col returns value of MarkdownImageData.border_col
func (self *MarkdownImageData) Bordercol() imgui.Vec4 {
	selfArg, selfFin := self.Handle()

	defer func() {
		selfFin()
	}()
	return func() imgui.Vec4 {
		out := C.wrap_MarkdownImageData_GetBorder_col(internal.ReinterpretCast[*C.MarkdownImageData](selfArg))
		return *(&imgui.Vec4{}).FromC(unsafe.Pointer(&out))
	}()
}

// MarkdownLinkCallbackData_SetText sets value of MarkdownLinkCallbackData.text
func (self MarkdownLinkCallbackData) SetText(v string) {
	vArg, _ := internal.WrapString[C.char](v)

	selfArg, selfFin := self.Handle()
	defer selfFin()
	C.wrap_MarkdownLinkCallbackData_SetText(selfArg, vArg)
}

// MarkdownLinkCallbackData_GetText returns value of MarkdownLinkCallbackData.text
func (self *MarkdownLinkCallbackData) Text() string {
	selfArg, selfFin := self.Handle()

	defer func() {
		selfFin()
	}()
	return func() string {
		result := C.wrap_MarkdownLinkCallbackData_GetText(internal.ReinterpretCast[*C.MarkdownLinkCallbackData](selfArg))
		defer C.free(unsafe.Pointer(result))
		return C.GoString(result)
	}()
}

// MarkdownLinkCallbackData_SetTextLength sets value of MarkdownLinkCallbackData.textLength
func (self MarkdownLinkCallbackData) SetTextLength(v int32) {
	selfArg, selfFin := self.Handle()
	defer selfFin()
	C.wrap_MarkdownLinkCallbackData_SetTextLength(selfArg, C.int(v))
}

// MarkdownLinkCallbackData_GetTextLength returns value of MarkdownLinkCallbackData.textLength
func (self *MarkdownLinkCallbackData) TextLength() int32 {
	selfArg, selfFin := self.Handle()

	defer func() {
		selfFin()
	}()
	return int32(C.wrap_MarkdownLinkCallbackData_GetTextLength(internal.ReinterpretCast[*C.MarkdownLinkCallbackData](selfArg)))
}

// MarkdownLinkCallbackData_SetLink sets value of MarkdownLinkCallbackData.link
func (self MarkdownLinkCallbackData) SetLink(v string) {
	vArg, _ := internal.WrapString[C.char](v)

	selfArg, selfFin := self.Handle()
	defer selfFin()
	C.wrap_MarkdownLinkCallbackData_SetLink(selfArg, vArg)
}

// MarkdownLinkCallbackData_GetLink returns value of MarkdownLinkCallbackData.link
func (self *MarkdownLinkCallbackData) Link() string {
	selfArg, selfFin := self.Handle()

	defer func() {
		selfFin()
	}()
	return func() string {
		result := C.wrap_MarkdownLinkCallbackData_GetLink(internal.ReinterpretCast[*C.MarkdownLinkCallbackData](selfArg))
		defer C.free(unsafe.Pointer(result))
		return C.GoString(result)
	}()
}

// MarkdownLinkCallbackData_SetLinkLength sets value of MarkdownLinkCallbackData.linkLength
func (self MarkdownLinkCallbackData) SetLinkLength(v int32) {
	selfArg, selfFin := self.Handle()
	defer selfFin()
	C.wrap_MarkdownLinkCallbackData_SetLinkLength(selfArg, C.int(v))
}

// MarkdownLinkCallbackData_GetLinkLength returns value of MarkdownLinkCallbackData.linkLength
func (self *MarkdownLinkCallbackData) LinkLength() int32 {
	selfArg, selfFin := self.Handle()

	defer func() {
		selfFin()
	}()
	return int32(C.wrap_MarkdownLinkCallbackData_GetLinkLength(internal.ReinterpretCast[*C.MarkdownLinkCallbackData](selfArg)))
}

// MarkdownLinkCallbackData_SetUserData sets value of MarkdownLinkCallbackData.userData
func (self MarkdownLinkCallbackData) SetUserData(v uintptr) {
	selfArg, selfFin := self.Handle()
	defer selfFin()
	C.wrap_MarkdownLinkCallbackData_SetUserData(selfArg, C.uintptr_t(v))
}

// MarkdownLinkCallbackData_GetUserData returns value of MarkdownLinkCallbackData.userData
func (self *MarkdownLinkCallbackData) UserData() uintptr {
	selfArg, selfFin := self.Handle()

	defer func() {
		selfFin()
	}()
	return uintptr(C.wrap_MarkdownLinkCallbackData_GetUserData(internal.ReinterpretCast[*C.MarkdownLinkCallbackData](selfArg)))
}

// MarkdownLinkCallbackData_SetIsImage sets value of MarkdownLinkCallbackData.isImage
func (self MarkdownLinkCallbackData) SetIsImage(v bool) {
	selfArg, selfFin := self.Handle()
	defer selfFin()
	C.wrap_MarkdownLinkCallbackData_SetIsImage(selfArg, C.bool(v))
}

// MarkdownLinkCallbackData_GetIsImage returns value of MarkdownLinkCallbackData.isImage
func (self *MarkdownLinkCallbackData) IsImage() bool {
	selfArg, selfFin := self.Handle()

	defer func() {
		selfFin()
	}()
	return C.wrap_MarkdownLinkCallbackData_GetIsImage(internal.ReinterpretCast[*C.MarkdownLinkCallbackData](selfArg)) == C.bool(true)
}

// MarkdownTooltipCallbackData_SetLinkData sets value of MarkdownTooltipCallbackData.linkData
func (self MarkdownTooltipCallbackData) SetLinkData(v MarkdownLinkCallbackData) {
	vArg, _ := v.C()

	selfArg, selfFin := self.Handle()
	defer selfFin()
	C.wrap_MarkdownTooltipCallbackData_SetLinkData(selfArg, internal.ReinterpretCast[C.MarkdownLinkCallbackData](vArg))
}

// MarkdownTooltipCallbackData_GetLinkData returns value of MarkdownTooltipCallbackData.linkData
func (self *MarkdownTooltipCallbackData) LinkData() MarkdownLinkCallbackData {
	selfArg, selfFin := self.Handle()

	defer func() {
		selfFin()
	}()
	return *NewMarkdownLinkCallbackDataFromC(func() *C.MarkdownLinkCallbackData {
		result := C.wrap_MarkdownTooltipCallbackData_GetLinkData(internal.ReinterpretCast[*C.MarkdownTooltipCallbackData](selfArg))
		return &result
	}())
}

// MarkdownTooltipCallbackData_SetLinkIcon sets value of MarkdownTooltipCallbackData.linkIcon
func (self MarkdownTooltipCallbackData) SetLinkIcon(v string) {
	vArg, _ := internal.WrapString[C.char](v)

	selfArg, selfFin := self.Handle()
	defer selfFin()
	C.wrap_MarkdownTooltipCallbackData_SetLinkIcon(selfArg, vArg)
}

// MarkdownTooltipCallbackData_GetLinkIcon returns value of MarkdownTooltipCallbackData.linkIcon
func (self *MarkdownTooltipCallbackData) LinkIcon() string {
	selfArg, selfFin := self.Handle()

	defer func() {
		selfFin()
	}()
	return func() string {
		result := C.wrap_MarkdownTooltipCallbackData_GetLinkIcon(internal.ReinterpretCast[*C.MarkdownTooltipCallbackData](selfArg))
		defer C.free(unsafe.Pointer(result))
		return C.GoString(result)
	}()
}

// TextBlock_SetStart sets value of TextBlock.start
func (self TextBlock) SetStart(v int32) {
	selfArg, selfFin := self.Handle()
	defer selfFin()
	C.wrap_TextBlock_SetStart(selfArg, C.int(v))
}

// TextBlock_GetStart returns value of TextBlock.start
func (self *TextBlock) Start() int32 {
	selfArg, selfFin := self.Handle()

	defer func() {
		selfFin()
	}()
	return int32(C.wrap_TextBlock_GetStart(internal.ReinterpretCast[*C.TextBlock](selfArg)))
}

// TextBlock_SetStop sets value of TextBlock.stop
func (self TextBlock) SetStop(v int32) {
	selfArg, selfFin := self.Handle()
	defer selfFin()
	C.wrap_TextBlock_SetStop(selfArg, C.int(v))
}

// TextBlock_GetStop returns value of TextBlock.stop
func (self *TextBlock) Stop() int32 {
	selfArg, selfFin := self.Handle()

	defer func() {
		selfFin()
	}()
	return int32(C.wrap_TextBlock_GetStop(internal.ReinterpretCast[*C.TextBlock](selfArg)))
}
